language: python
python:
- '2.7'
- '3.4'
install:

     # Install miniconda for python 2.7
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a


  # Install
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - conda install -n test-environment pandas>=0.18 requests==2.9.1
  - source activate test-environment
  - python setup.py install
  - pip install -r requirements.txt
  - pip install coveralls
script: nosetests
deploy:
  provider: pypi
  user: Anna.Schneider
  password:
    secure: SHHMXoR9TEeWyarMLSoPEP1MFCOawTAgFTaBuLAMu7nGVk0+HbwD78MiAd6k7LaSYj+huL8/B6JKWgY36b2liS33EzJUkaMtS9vt/RzTZUJix/rJepZ4d+6e+rAr+DL/ulCUGot8ILK6vO0S1BzlcQYyXJsc01LzngFDcVWY6sA=
  on:
    tags: true
    repo: WattTime/pyiso
after_success:
e - coveralls
